name: project_faceid3
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

   #SVG image
  flutter_svg: ^1.0.3

  cupertino_icons: ^1.0.4
  hexcolor: ^2.0.6
  font_awesome_flutter: ^10.1.0
  otp_text_field: ^1.1.2

  #Firebase auth & firebase core
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0

  #Google Sign-in
  google_sign_in: ^5.2.4
  #Cloud
  cloud_firestore: ^3.1.11

  fluttertoast: ^8.0.9

  #Stream Chat
  stream_chat_flutter: ^3.5.1

# switch animation between light and dark theme
  animated_theme_switcher: ^2.0.6

  # persist locally data
  shared_preferences: ^2.0.13

  # pick image
  image_picker: ^0.8.2


  # store image
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


